### ISSUE TITLE
lualibs 2.75 creates corrupt gzip files

### ISSUE THREAD

**Issue by pkl97** [latex3/lualibs#7] opened 2023-04-29 12:02 UTC
In recent TeXLive installations (since the lualibs 2.75 upgrade) luaotfload creates corrupt gzip files.

> [user@host]$ gunzip luaotfload-names.lua.gz
> gzip: luaotfload-names.lua.gz: invalid compressed data--crc error
> gzip: luaotfload-names.lua.gz: invalid compressed data--length error
> 
> [user@host]$ gunzip luaotfload-names.luc.gz
> gzip: luaotfload-names.luc.gz: invalid compressed data--crc error
> gzip: luaotfload-names.luc.gz: invalid compressed data--length error
> 

gzip is unable to extract the font database files.
On closer inspection (according to the gzip spec https://datatracker.ietf.org/doc/html/rfc1952) the timestamp, CRC32 checksum and file size in the created .gz files are all 32 bit zero values.

The reason are the 3 tocardinal4() calls in putcompressed() (file lualibs-util-zip.lua):

> putcompressed = function(str,level,originalname)
>         return concat {
>             identifier, -- 2 identifier
>             tocardinal1(0x08), -- 1 method
>             tocardinal1(0x08), -- 1 flags
>             tocardinal4(os.time()), -- 4 mtime  <-------- here
>             tocardinal1(0x02), -- 1 compression (2 or 4)
>             tocardinal1(0xFF), -- 1 operating
>             (originalname or "unknownname") .. "\0",
>             compress(str,level,nil,gzipwindow),
>             tocardinal4(zlibchecksum(str)), -- 4  <-------- here
>             tocardinal4(#str), -- 4  <-------- here
>         }

The implementation of the tocardinal"N"() methods for N>1 seems to be incorrect (file lualibs-util-sac.lua):

> function streams.tocardinal4le(n) return char(extract(0,8),extract(8,8),extract(16,8),extract(24,8)) end

The function argument "n" is not used.
Shouldn't it be like this?

> function streams.tocardinal4le(n) return char(extract(n,0,8),extract(n,8,8),extract(n,16,8),extract(n,24,8)) end

If I apply this change, the values are written as expected and gzip no longer complains.

**Comment by josephwright** [comment] 2023-05-04 16:14
The lines here are from 0ab8139b0dde2a9317b71893cfca120cbcedc222, which suggests the issue is in ConTeXt's code, as this is marked as an import.

**Comment by pkl97** [comment] 2023-05-05 18:56
I reported the issue to Hans Hagen and he fixed it in ConTeXt (see https://github.com/contextgarden/context/commit/c6aa01b932acbadd1b90b923d871400dfa1ea307).

So lualibs could make a new pull and fix the issue as well.

Just to mention it: He told me that the code in question is not used in ConTeXt and so is not tested

**Comment by pkl97** [comment] 2023-08-25 10:44
These two commits from the latest ConTeXt pull fixed the issue for lualibs 2.76:

- https://github.com/latex3/lualibs/commit/da15e90b80c258ed66956e31d8a66a3c8961739d
- https://github.com/latex3/lualibs/commit/d339da5b45049f00b0201b64d7f6db30cb439c1d

So I'll close the issue.

**Comment by pkl97** [comment] 2023-08-25 10:48
Closing

**Closed as completed** 2023-08-25 10:54 UTC
