### ISSUE TITLE
table.insert(package.loaders, 2, mylualoader) now causes problems

### ISSUE THREAD

**Issue by edrx** [latex3/lualibs#4] opened 2020-11-05 15:33 UTC
I am getting a strange error with TeXLive 2020 in my machine that I don't get with TeXLive 2019. The error is:

````
  .../2020/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:378:
    attempt to call a nil value (field 'cpath specification')
  stack traceback:
  .../2020/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:378:
    in local 'lookup'
  .../2020/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:402:
    in function
<.../2020/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua:392>
        [C]: in function 'require'
        dednat6/dednat6.lua:58: in main chunk
        [C]: in function 'dofile'
        dednat6load.lua:58: in main chunk
        [C]: in function 'dofile'
        [\directlua]:1: in main chunk.
  l.50 \directlua{dofile "dednat6load.lua"}
````

and what I understood after a few hours trying to debug this is that the culprit on my side is this chunk of code:

````
  package.loaders = package.loaders or package.searchers
  local function lualoader(modulename) ... end
  table.insert(package.loaders, 2, lualoader)
````

in this file:

  http://angg.twu.net/dednat6/dednat6/lualoader.lua.html

it seems that my code confuses the part of the code in

````
/usr/local/texlive/2020/texmf-dist/tex/luatex/lualibs/lualibs-basic-merged.lua
````

that comes from lualibs-package.lua... I tkdiff'ed the versions of lualibs-package.lua from TeXLive 2019 and TeXLive 2020 by doing

````
tkdiff \
  /usr/local/texlive/2019/texmf-dist/tex/luatex/lualibs/lualibs-package.lua \
  /usr/local/texlive/2020/texmf-dist/tex/luatex/lualibs/lualibs-package.lua
````

and I found that the function "helpers" contains this code,

````
  builtin    = {
      ["preload table"]       = searchers[1+offset], -- special case, built-in libs
      ["path specification"]  = searchers[2+offset],
      ["cpath specification"] = searchers[3+offset],
      ["all in one fallback"] = searchers[4+offset], -- special case, combined libs
  },
````

that supposes that users will not insert their own functions in the middle of the table package.searchers... but there's a LOT in the code in lualibs-package.lua that I don't understand - including the parts that changed from 2019 to 2020.

What should I do? Should I change my code that adds a new searcher to package.searchers? How? All the users of Dednat6 that I have conctact with use Dednat6 both on recent TeXLives and on TeXLive 2016/2017 - for Arxiv-related reasons - so I need to find a solution that works on as many versions of TeXLive as possible...

  Thanks in advance!
    Eduardo Ochs
    http://angg.twu.net/dednat6.html
    http://angg.twu.net/math-b.html

P.S.: this is a copy of: https://tug.org/pipermail/luatex/2020-November/007426.html

**Comment by zauguin** [comment] 2020-11-05 18:10
> and I found that the function "helpers" contains this code,
> 
> ```
>   builtin    = {
>       ["preload table"]       = searchers[1+offset], -- special case, built-in libs
>       ["path specification"]  = searchers[2+offset],
>       ["cpath specification"] = searchers[3+offset],
>       ["all in one fallback"] = searchers[4+offset], -- special case, combined libs
>   },
> ```
> 
> that supposes that users will not insert their own functions in the middle of the table package.searchers... but there's a LOT in the code in lualibs-package.lua that I don't understand - including the parts that changed from 2019 to 2020.

It's actually not the function `helpers`, it's the variable `helpers`. This is relevant because it means that the code in question only runs once before any document code is executed, therefore other searchers would not be registered yet and therefore the fixed indices are not a problem.

The issue you are currently facing is the same as the cause of #2: `lualibs-package.lua` adds a new searcher at position 1 (which basically replicates the predefined searchers with some additional options) but this does not verify that all of the predefined searchers are actually present. Starting with TeXLive 2020 the cpath and all-in-one searchers (by default index 3 and 4) are no longer predefined and therefore a non-existing functions is called whenever the first searcher hasn't found the file, therefore never executing later searchers.

Mostly this means that we have to fix that bug (I mistakenly thought that it's already fixed) and then your original code works again *but* the "old" helpers will have higher priority. (Basically it will act as if you inserted your searcher at the end and not at position 2. You could avoid this by actually using the mechanism provided by `lualibs-package.lua`. This should also allow you to set your system only be active until your package is loaded and therefore avoid messing up the searchers for the full run.)

**Comment by zauguin** [comment] 2021-01-01 12:07
This is fixed in the latest version.

**Closed as completed by zauguin** 2021-01-01 12:07 UTC
